//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 xsd 自动生成, Version=4.0.30319.17929。
// 
namespace XMCares.BMS.FDI.Model {
    using System.Xml.Serialization;

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "schema.aiis.maiis.iport")]
    [System.Xml.Serialization.XmlRootAttribute(ElementName = "AIIS", Namespace = "schema.aiis.maiis.iport", IsNullable = false)]
    public class AIISBASE
    {
        private META mETAField;

        private FLIGHTMOVEMENT fLIGHTMOVEMENTField;

        /// <remarks/>
        public META META
        {
            get
            {
                return this.mETAField;
            }
            set
            {
                this.mETAField = value;
            }
        }

        /// <remarks/>
        public FLIGHTMOVEMENT FLIGHTMOVEMENT
        {
            get
            {
                return this.fLIGHTMOVEMENTField;
            }
            set
            {
                this.fLIGHTMOVEMENTField = value;
            }
        }
    }
}
